name: Automatically Deploy

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@master
        with:
          ref: master
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Build Code
        run: |
          npm i
          npm run build
      - name: Copy Code
        uses: ZeroKen5969/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./built/*
          target: ~/botenv/bot/built
          strip_components: 1
          overwrite: true
          rm: true
      - name: Run Code
        uses: ZeroKen5969/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ~/botenv
            chmod +x *.sh
            ./hotstart.sh